import { Board } from "./src/types/map";

export const initialBoards: Board[] = [
  {
    id: "b1",
    type: "board",
    coordinate: { latitude: 37.475, longitude: 126.936 },
    emoji: "☕",
    title: "모카하우스 신림점",
    description: "한산 시간 방문/체류 미션으로 코인을 받을 수 있어요.",
    createdAt: Date.now() - 100000,
    missions: [
      {
        id: "b1-m1",
        type: "quiet_time_visit",
        title: "한산 시간대 방문 인증",
        description: "오후 2시~4시 사이 방문 후 GPS 인증하면 코인을 드려요.",
        rewardCoins: 12,
      },
      {
        id: "b1-m2",
        type: "stay_duration",
        title: "30분 이상 체류",
        description: "체류 시작 버튼을 누른 뒤 30분 이상 머물고 종료하면 보상 지급.",
        rewardCoins: 35,
        minDurationMinutes: 30,
      },
    ],
  },
  {
    id: "b2",
    type: "board",
    coordinate: { latitude: 37.470, longitude: 126.942 },
    emoji: "🍔",
    title: "버거랩 보라매점",
    description: "점심 피크 이후 미션 참여 시 리워드를 받을 수 있어요.",
    createdAt: Date.now() - 200000,
    missions: [
      {
        id: "b2-m1",
        type: "quiet_time_visit",
        title: "한산 시간대 방문 인증",
        description: "평일 3시 이후 매장 방문 시 GPS 인증하면 코인 지급.",
        rewardCoins: 10,
      },
      {
        id: "b2-m2",
        type: "stay_duration",
        title: "20분 이상 체류",
        description: "시작/종료 시점 GPS를 기록해 20분 이상 체류를 검증합니다.",
        rewardCoins: 24,
        minDurationMinutes: 20,
      },
    ],
  },
  {
    id: "b3",
    type: "board",
    coordinate: { latitude: 37.468, longitude: 126.934 },
    emoji: "📚",
    title: "북스트리트 카페",
    description: "독서 고객 유입을 위한 체류 중심 미션입니다.",
    createdAt: Date.now() - 300000,
    missions: [
      {
        id: "b3-m1",
        type: "quiet_time_visit",
        title: "한산 시간대 방문 인증",
        description: "오전 10시~12시 사이 방문 인증 시 코인 보상.",
        rewardCoins: 9,
      },
      {
        id: "b3-m2",
        type: "stay_duration",
        title: "40분 이상 체류",
        description: "조용한 좌석에서 40분 이상 체류 후 GPS 검증.",
        rewardCoins: 42,
        minDurationMinutes: 40,
      },
    ],
  },
  {
    id: "b4",
    type: "board",
    coordinate: { latitude: 37.474, longitude: 126.933 },
    emoji: "🥗",
    title: "그린샐러드 스튜디오",
    description: "오프피크 방문과 체류 미션 두 가지가 열려 있어요.",
    createdAt: Date.now() - 400000,
    missions: [
      {
        id: "b4-m1",
        type: "quiet_time_visit",
        title: "한산 시간대 방문 인증",
        description: "오후 4시~5시 방문 후 GPS 인증 완료 시 코인 적립.",
        rewardCoins: 11,
      },
      {
        id: "b4-m2",
        type: "stay_duration",
        title: "25분 이상 체류",
        description: "체류 시작/종료 버튼으로 25분 이상 체류를 인증하세요.",
        rewardCoins: 28,
        minDurationMinutes: 25,
      },
    ],
  },
];
