import { Dimensions, Platform, StyleSheet } from "react-native";

const screenWidth = Dimensions.get("window").width;
const actionButtonBottom = Platform.OS === "android" ? 76 : 30;
const authButtonBottom = actionButtonBottom + 58;
const locationButtonBottom = actionButtonBottom + 116;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8F9FA", justifyContent: "center", alignItems: "center" },
  searchContainer: {
    position: "absolute",
    top: 55,
    width: "90%",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    zIndex: 20,
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: "#212529",
  },
  loadingOverlay: {
    position: "absolute",
    top: 108,
    alignSelf: "center",
    backgroundColor: "rgba(19, 29, 48, 0.85)",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    zIndex: 20,
  },
  loadingOverlayText: {
    color: "#f6f7fb",
    fontSize: 12,
    fontWeight: "700",
  },
  authInput: {
    borderWidth: 1,
    borderColor: "#d5dfef",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 9,
    color: "#212529",
    marginBottom: 8,
    backgroundColor: "#fbfcff",
  },
  authInputNoMargin: {
    marginBottom: 0,
  },
  authActionDisabled: {
    opacity: 0.6,
  },
  authFloatingButton: {
    position: "absolute",
    right: 30,
    bottom: authButtonBottom,
    width: 96,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#355fa5",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 10,
  },
  authFloatingButtonText: {
    color: "white",
    fontWeight: "800",
    fontSize: 12,
    marginLeft: 6,
    letterSpacing: 0,
  },
  map: { ...StyleSheet.absoluteFillObject },
  markerContainer: {
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 4,
    minHeight: 42,
  },
  emojiMarker: {
    fontSize: 30,
    lineHeight: 38,
    includeFontPadding: true,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalView: {
    width: "80%",
    backgroundColor: "white",
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 15,
  },
  input: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    padding: 10,
    marginBottom: 15,
    color: "#212529",
  },
  textArea: {
    height: 100,
    textAlignVertical: "top",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  button: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
    marginHorizontal: 5,
  },
  cancelButton: {
    backgroundColor: "#ccc",
  },
  modalCloseButton: {
    backgroundColor: "#8a8f99",
  },
  saveButton: {
    backgroundColor: "#007BFF",
  },
  buttonText: {
    color: "white",
    fontWeight: "bold",
  },
  instructionBanner: {
    position: "absolute",
    top: 120,
    backgroundColor: "rgba(0,0,0,0.7)",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    zIndex: 10,
  },
  instructionText: {
    color: "white",
    fontWeight: "bold",
  },
  addButton: {
    position: "absolute",
    bottom: 30,
    right: 30,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#FF5A5F",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 10,
  },
  myLocationButton: {
    position: "absolute",
    right: 30,
    bottom: locationButtonBottom,
    width: 96,
    height: 44,
    borderRadius: 22,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#d7e6ff",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
    paddingHorizontal: 12,
    zIndex: 10,
  },
  myLocationButtonText: {
    color: "#0d6efd",
    fontWeight: "800",
    fontSize: 12,
    marginLeft: 6,
    letterSpacing: 0,
  },
  myActivitiesButton: {
    position: "absolute",
    right: 30,
    bottom: actionButtonBottom,
    width: 96,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#007BFF",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 10,
  },
  myActivitiesButtonText: {
    color: "white",
    fontWeight: "800",
    fontSize: 12,
    marginLeft: 6,
    letterSpacing: 0,
  },
  photoButton: {
    backgroundColor: "#E9ECEF",
    padding: 10,
    borderRadius: 8,
    flex: 1,
    alignItems: "center",
    marginBottom: 10,
    marginHorizontal: 4,
  },
  photoButtonText: {
    color: "#495057",
    fontWeight: "bold",
  },
  photoActionRow: {
    width: "100%",
    flexDirection: "row",
    marginBottom: 6,
  },
  previewImage: {
    width: "100%",
    height: 150,
    borderRadius: 8,
    marginBottom: 15,
  },
  previewMetaText: {
    fontSize: 12,
    color: "#5f6d85",
    marginTop: -8,
    marginBottom: 14,
  },
  cameraContainer: {
    flex: 1,
    backgroundColor: "black",
  },
  cameraView: {
    flex: 1,
  },
  cameraControls: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingTop: 14,
    paddingBottom: 24,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
  },
  cameraControlButton: {
    marginHorizontal: 4,
  },
  viewModalContent: {
    width: "85%",
    backgroundColor: "white",
    borderRadius: 20,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  typeSelector: {
    flexDirection: "row",
    marginBottom: 15,
    width: "100%",
    borderRadius: 8,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#007BFF",
  },
  typeButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    backgroundColor: "white",
  },
  typeButtonActive: {
    backgroundColor: "#007BFF",
  },
  typeButtonText: {
    color: "#007BFF",
    fontWeight: "bold",
  },
  typeButtonTextActive: {
    color: "white",
  },
  boardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
    width: "100%",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    paddingBottom: 10,
  },
  boardEmoji: {
    fontSize: 40,
    marginRight: 15,
  },
  boardTitle: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 5,
  },
  boardDescription: {
    fontSize: 14,
    color: "#666",
  },
  boardTabContainer: {
    width: "100%",
    flexDirection: "row",
    backgroundColor: "#eef2fb",
    borderRadius: 10,
    padding: 3,
    marginBottom: 10,
  },
  boardTabButton: {
    flex: 1,
    borderRadius: 8,
    paddingVertical: 8,
    alignItems: "center",
  },
  boardTabButtonActive: {
    backgroundColor: "white",
  },
  boardTabText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#51617d",
  },
  boardTabTextActive: {
    color: "#0d6efd",
  },
  boardImage: {
    width: "100%",
    height: 150,
    borderRadius: 10,
    marginBottom: 15,
  },
  boardPostsContainer: {
    width: "100%",
    minHeight: 120,
    maxHeight: 260,
    marginBottom: 15,
    flexShrink: 1,
  },
  boardPostItem: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    backgroundColor: "#f9f9f9",
    borderRadius: 8,
    marginBottom: 10,
  },
  boardPostTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 5,
  },
  boardPostEmoji: {
    fontSize: 18,
    marginRight: 6,
  },
  boardPostTitle: {
    fontSize: 16,
    fontWeight: "bold",
  },
  boardPostPreview: {
    fontSize: 14,
    color: "#555",
    marginBottom: 5,
  },
  boardPostTime: {
    fontSize: 12,
    color: "#999",
    textAlign: "right",
  },
  inlineBoardPostContainer: {
    width: "100%",
    marginTop: 10,
    paddingTop: 10,
    flexShrink: 1,
  },
  modalTopBar: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    position: "relative",
    marginBottom: 10,
  },
  backButtonInline: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 2,
  },
  backButtonInlineText: {
    fontSize: 12,
    color: "#8b8b8b",
    fontWeight: "600",
    marginLeft: 4,
  },
  swipeHintContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  topBarCenterHint: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  topBarSpacer: {
    width: 56,
  },
  swipeHintText: {
    fontSize: 12,
    color: "#8b8b8b",
    fontWeight: "600",
    marginLeft: 4,
  },
  viewModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    paddingBottom: 10,
  },
  viewModalEmoji: {
    fontSize: 30,
    marginRight: 10,
  },
  viewModalTitle: {
    fontSize: 20,
    fontWeight: "bold",
  },
  timerText: {
    fontSize: 12,
    color: "#FF5A5F",
    marginTop: 4,
    fontWeight: "bold",
  },
  viewModalImage: {
    width: "100%",
    height: 200,
    borderRadius: 10,
    marginBottom: 15,
  },
  viewModalDescription: {
    fontSize: 16,
    lineHeight: 24,
    color: "#333",
    marginBottom: 20,
  },
  commentsSection: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#eee",
    paddingTop: 15,
  },
  commentsTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 10,
  },
  commentItem: {
    backgroundColor: "#f8f9fa",
    padding: 10,
    borderRadius: 8,
    marginBottom: 8,
  },
  commentText: {
    fontSize: 14,
    color: "#333",
  },
  commentTime: {
    fontSize: 10,
    color: "#999",
    marginTop: 4,
    textAlign: "right",
  },
  noCommentsText: {
    color: "#999",
    fontStyle: "italic",
    textAlign: "center",
    marginVertical: 10,
  },
  commentInputContainer: {
    flexDirection: "row",
    marginTop: 15,
    alignItems: "center",
  },
  commentInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 20,
    paddingHorizontal: 15,
    paddingVertical: 8,
    marginRight: 10,
    color: "#212529",
  },
  commentSubmitButton: {
    backgroundColor: "#007BFF",
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  missionListContainer: {
    width: "100%",
    maxHeight: 360,
  },
  missionListContent: {
    paddingBottom: 8,
  },
  guestbookContainer: {
    width: "100%",
    maxHeight: 360,
  },
  guestbookListContainer: {
    width: "100%",
    maxHeight: 250,
  },
  guestbookListContent: {
    paddingBottom: 8,
  },
  guestbookItem: {
    backgroundColor: "#f7f9fc",
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#e4e9f5",
  },
  guestbookItemText: {
    fontSize: 14,
    color: "#222",
    lineHeight: 20,
  },
  guestbookItemTime: {
    marginTop: 4,
    fontSize: 11,
    color: "#6b7486",
    textAlign: "right",
  },
  guestbookEmptyText: {
    color: "#999",
    fontStyle: "italic",
    textAlign: "center",
    marginTop: 24,
  },
  guestbookInputSection: {
    marginTop: 6,
    borderTopWidth: 1,
    borderTopColor: "#eceff4",
    paddingTop: 10,
  },
  guestbookInput: {
    borderWidth: 1,
    borderColor: "#d3dbea",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#212529",
    backgroundColor: "white",
  },
  guestbookInputFooter: {
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  guestbookCounter: {
    fontSize: 12,
    color: "#6a7388",
  },
  guestbookSubmitButton: {
    minWidth: 70,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: "#007BFF",
    alignItems: "center",
  },
  guestbookSubmitButtonDisabled: {
    backgroundColor: "#9fbde8",
  },
  boardActivitySection: {
    backgroundColor: "#f3f7ff",
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#dbe7ff",
  },
  boardActivitySectionTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#1f3f75",
    marginBottom: 8,
  },
  boardActivityEmptyText: {
    fontSize: 12,
    color: "#6a778f",
  },
  boardActivityItem: {
    backgroundColor: "white",
    borderRadius: 8,
    padding: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#e1e8f7",
  },
  boardActivityHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  boardActivityTitle: {
    flex: 1,
    fontSize: 12,
    fontWeight: "700",
    color: "#1f2b3d",
    marginRight: 8,
  },
  boardActivityStatus: {
    fontSize: 11,
    fontWeight: "700",
    color: "#335ea8",
  },
  boardActivityMeta: {
    fontSize: 11,
    color: "#5f6d85",
    marginTop: 4,
  },
  boardActivityReceiptImage: {
    width: "100%",
    height: 120,
    borderRadius: 8,
    marginTop: 8,
  },
  missionCard: {
    backgroundColor: "#f8f9ff",
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#e4e9ff",
  },
  missionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  missionEmoji: {
    fontSize: 18,
    marginRight: 8,
  },
  missionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#222",
  },
  missionTypeText: {
    fontSize: 12,
    color: "#53607a",
    marginTop: 1,
  },
  missionRewardText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#0d6efd",
  },
  missionDescription: {
    fontSize: 13,
    color: "#444",
    lineHeight: 18,
    marginBottom: 6,
  },
  missionRuleText: {
    fontSize: 12,
    color: "#616161",
    marginBottom: 8,
  },
  missionActionContainer: {
    marginTop: 4,
  },
  missionCompletedText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0a9d58",
  },
  missionCompletedContainer: {
    width: "100%",
  },
  missionReceiptPreviewImage: {
    width: "100%",
    height: 140,
    borderRadius: 10,
    marginTop: 8,
  },
  missionReceiptMetaText: {
    fontSize: 12,
    color: "#5f6d85",
    marginTop: 6,
  },
  missionTreasureGuideContainer: {
    width: "100%",
    marginBottom: 6,
  },
  missionTreasureGuideImage: {
    width: "100%",
    height: 96,
    borderRadius: 10,
    marginTop: 4,
  },
  missionProgressContainer: {
    width: "100%",
  },
  missionProgressText: {
    fontSize: 12,
    color: "#616161",
    marginBottom: 6,
  },
  stampMissionContainer: {
    width: "100%",
  },
  stampRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  stampDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "#b7c2d7",
    backgroundColor: "#ffffff",
    marginRight: 6,
  },
  stampDotFilled: {
    backgroundColor: "#0d6efd",
    borderColor: "#0d6efd",
  },
  activitiesModalView: {
    width: "88%",
    maxHeight: "80%",
    backgroundColor: "white",
    borderRadius: 20,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  activitiesList: {
    width: "100%",
    marginBottom: 12,
  },
  coinOverviewCard: {
    width: "100%",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#cfe0ff",
    backgroundColor: "#eef4ff",
    padding: 10,
    marginBottom: 10,
  },
  coinOverviewTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: "#2d4e8a",
  },
  coinOverviewTotal: {
    marginTop: 4,
    fontSize: 18,
    fontWeight: "800",
    color: "#0d4ed1",
  },
  coinOverviewMeta: {
    marginTop: 2,
    fontSize: 12,
    color: "#4b5e82",
  },
  activityItem: {
    padding: 12,
    backgroundColor: "#f7f9fc",
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#e8edf5",
  },
  activityHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  activityTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: "700",
    color: "#222",
    marginRight: 8,
  },
  activityStatusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  activityStatusStarted: {
    backgroundColor: "#e8f0ff",
  },
  activityStatusCompleted: {
    backgroundColor: "#e2f8eb",
  },
  activityStatusText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#25406e",
  },
  activityMetaText: {
    fontSize: 12,
    color: "#555",
    marginTop: 2,
  },
  participatedStoreItem: {
    padding: 12,
    backgroundColor: "#f7f9fc",
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#e8edf5",
  },
  participatedStoreHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  participatedStoreEmoji: {
    fontSize: 20,
    marginRight: 8,
  },
  participatedStoreTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#222",
  },
  participatedStoreDescription: {
    fontSize: 12,
    color: "#51617d",
    lineHeight: 17,
    marginTop: 2,
    marginBottom: 4,
  },
  participatedStoreMeta: {
    fontSize: 12,
    color: "#555",
    marginTop: 2,
  },
  participatedStoreStampMeta: {
    fontSize: 12,
    color: "#1f4f9a",
    fontWeight: "700",
    marginTop: 2,
  },
  participatedStoreStampWrap: {
    marginTop: 6,
  },
  participatedStoreActivitySection: {
    marginTop: 8,
    backgroundColor: "#eef3ff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#d9e4fb",
    padding: 8,
  },
  participatedStoreActivitySectionTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: "#25406e",
    marginBottom: 6,
  },
  participatedStoreActivityItem: {
    backgroundColor: "white",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#dfe7f6",
    padding: 8,
    marginBottom: 6,
  },
  participatedStoreActivityHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  participatedStoreActivityRight: {
    alignItems: "flex-end",
    marginLeft: 8,
  },
  participatedStoreActivityTitle: {
    flex: 1,
    marginRight: 8,
    fontSize: 12,
    fontWeight: "700",
    color: "#1f2b3d",
  },
  participatedStoreActivityReward: {
    fontSize: 11,
    fontWeight: "800",
    color: "#0a9d58",
  },
  participatedStoreActivityRewardStamp: {
    color: "#5f6d85",
  },
  participatedStoreActivityStatus: {
    fontSize: 11,
    fontWeight: "700",
    color: "#2c5fb3",
    marginTop: 2,
  },
  participatedStoreActivityMeta: {
    marginTop: 4,
    fontSize: 11,
    color: "#5f6d85",
  },
  participatedStoreActivityMore: {
    marginTop: 2,
    fontSize: 11,
    color: "#51617d",
  },
});

export { screenWidth };
